### ISSUE TITLE
Add navigation from a test into the Test Explorer window to the corresponding feature file

### ISSUE THREAD

**Issue by plv2** [specsolutions/deveroom-feedback#12]
Propose a way to make possible code navigation from VisualStudio Test Explorer window to corresponding feature code source.
For example double click or Ctrl+Click on a test into the Test Explorer windows navigate/open the corresponding feature.

**Comment by gasparnagy** [comment]
The navigation from the Test Explorer window is provided by the unit test visual studio adapters. I know that some adapters have/had some problems with this and there has been even a related issue on the [specflow github](https://github.com/techtalk/SpecFlow/issues), but I cannot find it now. 

I close this issue here, as Deveroom cannot help this, please reopen if you get any new info.

With a standard xUnit project it just works:

![image](https://user-images.githubusercontent.com/144701/54031685-be578600-41af-11e9-8a14-9daaa23bf0bf.png)
